version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - AWS_REGION=${AWS_REGION:-us-east-1}
      - AWS_ROLE_ARN=${AWS_ROLE_ARN}
      - AWS_ROLE_SESSION_NAME=${AWS_ROLE_SESSION_NAME:-config_manager_service}
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M 